feat: added range tx search when applicable
icon-project/ibc-relay pull request #228
Opened 2024-08-01 07:21 UTC by bcsainju

Added range tx search to get blocks and only sync related blocks when synchronizing

2024-08-01 07:39 UTC, sherpalden commented on relayer/chains/wasm/provider.go
> +	page := 1
let's create a small function to check if the RPC supports range query.

2024-08-01 07:39 UTC, sherpalden commented on relayer/chains/wasm/wasm_chain_processor.go
> +		resultArr = append(resultArr, tx.Height)
looks like there is a possibility of duplicate heights in the array when multiple txns are in the same block.

2024-08-01 07:53 UTC, sherpalden commented on relayer/chains/wasm/wasm_chain_processor.go
> +	perPage := int(50)
per page the API supports 100 txns, may be we can get max benefits by setting it to 100.

2024-08-01 07:54 UTC, bcsainju commented on relayer/chains/wasm/wasm_chain_processor.go
> +		resultArr = append(resultArr, tx.Height)
yes it might be a duplicate but since we use this to verify if x block should be processed or not, the actual processing wont be duplicate.

2024-08-01 08:01 UTC, sherpalden commented on relayer/chains/wasm/wasm_chain_processor.go
> +func (ccp *WasmChainProcessor) getBlocksToProcess(ctx context.Context, blockToRequest int64) ([]int64, error) {
lets return the block in ascending order and we don't need extra max block function. Also,  I think we need some control over the range of blocks to return from this function. Lets say our block to request is like 100, and lets say we got the max block like 10,000. In that case, may be its a good idea have a threshold limit like 1000 max blocks. Then we will only return blocks in range of block to request to 1000 blocks. This might be useful if we need to update light clients at least at particular interval of heights.

2024-08-01 08:04 UTC, bcsainju commented on relayer/chains/wasm/wasm_chain_processor.go
> +func (ccp *WasmChainProcessor) getBlocksToProcess(ctx context.Context, blockToRequest int64) ([]int64, error) {
since we aren't iterating over all pagination but only the first page of result in an iteration, we need max blocks. This makes us to be a bit slow on rpc but avoid getting rpc errors. other pages would be handled in next iteration itself.

2024-08-07 10:52 UTC, sherpalden submitted a review, later dismissed

2024-08-12 04:39 UTC, sherpalden requested changes

2024-08-12 04:39 UTC, sherpalden commented on relayer/chains/wasm/wasm_chain_processor.go
> +		blockToRequest, ibcHandlerAddr)
I think the placeholder value for height filter should be `blockToRequest-1`.

2024-08-12 05:10 UTC, bcsainju commented on relayer/chains/wasm/wasm_chain_processor.go
> +		blockToRequest, ibcHandlerAddr)
updated to use >= instead in the query.

2024-08-12 05:14 UTC, sherpalden submitted a review, later dismissed

2024-08-21 05:09 UTC, sherpalden approved these changes

2024-08-21 05:21 UTC, merged